version: "3.8"
services:
  php-app:
    image: php-app-image
    container_name: php-app
    restart: unless-stopped
    env_file:
      - .env
    tty: true
    ports:
      - "4000:80"
    networks:
      - php-app-net

networks:
  php-app-net:
    name: php-app-net
